2024-03-11 19:34:35,622 - root - INFO - Бот запущен
2024-03-11 19:34:42,962 - root - INFO - Отправка приветственного сообщения(/start)
2024-03-11 19:34:47,616 - root - INFO - Запрос в обработке.
2024-03-11 19:36:20,579 - root - INFO - Ответ пользователю успешно отправлен
2024-03-11 19:36:38,833 - root - INFO - Пользователь продолжил решение.
2024-03-11 19:36:39,912 - root - INFO - Запрос в обработке.
2024-03-11 19:38:15,375 - root - INFO - Ответ пользователю успешно отправлен
2024-03-11 19:38:18,905 - root - INFO - Пользователь продолжил решение.
2024-03-11 19:38:29,247 - root - INFO - Запрос в обработке.
2024-03-11 19:38:43,395 - root - INFO - Отправка вспомогательного сообщения(/help)
2024-03-11 19:38:53,850 - root - INFO - Ответ пользователю успешно отправлен
2024-03-11 19:38:54,110 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
2024-03-11 19:38:54,111 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\__init__.py", line 1141, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\util.py", line 149, in raise_exceptions
    raise self.exception_info
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "E:\GPThellper_bot.v.1\bot.py", line 118, in get_promt
    bot.send_message(message.chat.id, answer, reply_markup=keyboard)
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\__init__.py", line 1673, in send_message
    apihelper.send_message(
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\apihelper.py", line 264, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\apihelper.py", line 164, in _make_request
    json_result = _check_result(method_name, result)
  File "E:\GPThellper_bot.v.1\venv\lib\site-packages\telebot\apihelper.py", line 191, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty

